name: 'Upstream Sync'

on:
  schedule:
    - cron:  '30 0/6 * * *'
      timezone: "America/New_York"
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    name: Sync latest commits from upstream repo
    steps:

    - name: Checkout forked repo
      uses: actions/checkout@v6
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        fetch-depth: 0

    - name: Add upstream remote
      run: git remote add upstream https://github.com/FxEmbed/FxEmbed

    - name: Fetch upstream changes
      run: git fetch upstream

    - name: Rebase main and push
      run: |
        git config user.name ${{ vars.GIT_USER_NAME }}
        git config user.email ${{ vars.GIT_USER_EMAIL }}
        git checkout main
        git rebase -Xtheirs upstream/main
        git push origin main --force

