name: Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: '24.20.0'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm install
      - run: npm run build && npm test
